version: "3.7"
services:
  postgres:
    container_name: postgres
    hostname: postgres
    image: 'postgres:latest'
    ports:
      - "5432:5432"
      - "5433:5433"
    environment:
      POSTGRES_PASSWORD: password
      
  redis:
    container_name: redis
    hostname: redis
    image: 'redis:latest'
    ports:
      - "6379:6379"
  api:
    hostname: api
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - postgres
      - redis
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      APP_PORT: 3000
      JWT_SECRET: "aa5e8c36-7f46-4de1-a7bb-58c8d4909762"
      JWT_EXPIRATION: 1800
      SMTP_USER: "movierental.nodemailer@gmail.com"
      SMTP_PASS: "!Password1234*"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PGUSER: postgres
      PGHOST: postgres
      PGDATABASE: postgres
      PGPASSWORD: postgres
      PGPORT: 5432