apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: nestjs-api
  template:
    metadata:
      labels:
        app: nestjs-api
    spec:
      containers:
      - name: nestjs-api
        image: jrartiga/nestjs-api
        ports:
        - containerPort: 3000
        env:
          - name: REDIS_HOST
            value: 
          - name: REDIS_PORT
            value:
          - name: DB_HOST
            value: 
          - name: DB_PORT
            value:
          - name: DB_USER
            value: 
          - name: MYSQL_ROOT_PASSWORD
            value: 
          - name: MYSQL_DATABASE
            value: 

